# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-09 19:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahmoud_group', to='otree.Session')),
            ],
            options={
                'db_table': 'mahmoud_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('dump_q1', otree.db.models.StringField(max_length=10000, null=True)),
                ('dump_q3a', otree.db.models.StringField(max_length=10000, null=True)),
                ('dump_q3b', otree.db.models.StringField(max_length=10000, null=True)),
                ('dump_q3c', otree.db.models.StringField(max_length=10000, null=True)),
                ('selecting_q1', otree.db.models.IntegerField(null=True)),
                ('selecting_q3a', otree.db.models.IntegerField(null=True)),
                ('selecting_q3b', otree.db.models.IntegerField(null=True)),
                ('selecting_q3c', otree.db.models.IntegerField(null=True)),
                ('dice_q1_d1', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('dice_q1_d2', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('dice_q2', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('dice_q3a', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('dice_q3b', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('dice_q3c', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('profit_q1', otree.db.models.FloatField(null=True)),
                ('profit_q2', otree.db.models.FloatField(null=True)),
                ('profit_q3a', otree.db.models.FloatField(null=True)),
                ('profit_q3b', otree.db.models.FloatField(null=True)),
                ('profit_q3c', otree.db.models.FloatField(null=True)),
                ('question2a', otree.db.models.IntegerField(null=True, verbose_name='Keep (in CHF):')),
                ('question2b', otree.db.models.IntegerField(null=True, verbose_name='Play (in CHF):')),
                ('gender', otree.db.models.StringField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10000, null=True)),
                ('field_of_study', otree.db.models.StringField(choices=[('Economics/finance', 'Economics/finance'), ('Other ', 'Other ')], max_length=10000, null=True, verbose_name='Field of study')),
                ('level_of_study', otree.db.models.StringField(choices=[('Bachelor student', 'Bachelor student'), ('Master student', 'Master student')], max_length=10000, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name=' if you would like to be considered for the random reward, please enter your email here.')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mahmoud.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahmoud_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahmoud_player', to='otree.Session')),
            ],
            options={
                'db_table': 'mahmoud_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Q1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_n', otree.db.models.StringField(max_length=10000, null=True)),
                ('cost', otree.db.models.StringField(max_length=10000, null=True)),
                ('d1', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('d2', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rule', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('real_cost', otree.db.models.FloatField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahmoud_q1_question', to='mahmoud.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Q3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_a', otree.db.models.StringField(max_length=10000, null=True)),
                ('option_b', otree.db.models.StringField(max_length=10000, null=True)),
                ('answer', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('type', otree.db.models.StringField(max_length=10000, null=True)),
                ('A', otree.db.models.FloatField(null=True)),
                ('B_false', otree.db.models.FloatField(null=True)),
                ('B_true', otree.db.models.FloatField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahmoud_q3_question', to='mahmoud.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahmoud_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'mahmoud_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahmoud.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahmoud.Subsession'),
        ),
    ]
